apiVersion: v1
kind: Pod
metadata:
    name: client-pod
    labels:
        component: web
spec:
    containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
            # exposing port 3000 to the outside world
            
